### ISSUE TITLE
Cursor missing

### ISSUE THREAD

**Issue by AlexNsbmr** [ViksaaSkool/AutoFitEditText#1]
Would it be possible to add the cursor to your `EditText`?

**Comment by ViksaaSkool** [comment]
try [this](http://bit.ly/1SzwVp1)

**Comment by AlexNsbmr** [comment]
@ViksaaSkool Thank you. I tried this trick but it didn't work. Finally I used `android:textCursorDrawable` with a custom drawable and it worked.
